log:
  # log level: debug, info, warn, error
  log_level: "info"
  # log path
  log_path: "server0.log"

event_log:
  rtc_log_path: "rtc_event0.log"
  rtc_stream_log_path: "rtc_stream0.log"

#websocket server
websocket_server:
  # wss enable only when you have valid certificate and key files
  ssl_enable: false
  cert_path: "certificate.crt"
  key_path: "private.key"
  listen_ip: "0.0.0.0"
  port: 7443

#rtmp server
rtmp_server:
  enable: true
  listen_ip: "0.0.0.0"
  port: 1935

#http-flv server
httpflv_server:
  enable: true
  listen_ip: "0.0.0.0"
  port: 8080

#websocket stream server (flv over websocket)
ws_stream_server:
  enable: true
  listen_ip: "0.0.0.0"
  port: 8443

#webrtc
#candidates: [{nettype, ip, port}]
candidates:
  - nettype: "udp"
    candidate_ip: "192.168.1.221"
    listen_ip: "0.0.0.0"
    port: 5000
  - nettype: "udp"
    candidate_ip: "192.168.1.221"
    listen_ip: "0.0.0.0"
    port: 6000

cert_path: "certificate.crt"
key_path: "private.key"

whip_server:
  enable: true
  ssl_enable: false
  cert_path: "certificate.crt"
  key_path: "private.key"
  listen_ip: "0.0.0.0"
  port: 6443

downlink_discard_percent: 0
uplink_discard_percent: 0

pilot_center:
  enable: false
  host: "192.168.1.221"
  port: 9443
  subpath: "/pilot/center"

rtc_relay:
  relay_server_ip: "192.168.1.221"
  relay_udp_start: 10000
  relay_udp_end: 19999
  send_discard_percent: 0
  recv_discard_percent: 0

voice_agent:
  enable: true
  agent_ip: "192.168.1.221"
  agent_port: 5555
  subpath: "/voiceagent"

  # how to download:
  # wget https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/matcha-icefall-zh-baker.tar.bz2
  # tar xvf matcha-icefall-zh-baker.tar.bz2
  # rm matcha-icefall-zh-baker.tar.bz2  
  # wget https://github.com/k2-fsa/sherpa-onnx/releases/download/vocoder-models/vocos-22khz-univ.onnx
  tts_config:
    tts_enable: true
    acoustic_model: "./matcha-icefall-zh-baker/model-steps-3.onnx"
    vocoder: "./vocos-22khz-univ.onnx"
    lexicon: "./matcha-icefall-zh-baker/lexicon.txt"
    tokens: "./matcha-icefall-zh-baker/tokens.txt"
    dict_dir: "./matcha-icefall-zh-baker/dict"
    num_threads: 1